--+ 게시판 (board)
--
--게시글번호(pk) 제목 내용 작성자 작성일 IP status 조회수

 CREATE TABLE BOARD
 (BNO NUMBER(10) CONSTRAINT BOARD_BNO_2PK PRIMARY KEY,
 TITLE VARCHAR2(100),
 WRITER VARCHAR2(30),
 CONTENTS CLOB,
 REGDATE DATE,
 IP VARCHAR2(16),
 STATUS NUMBER(2),
 HITS NUMBER(5));

CREATE SEQUENCE BOARD_BNO_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCYCLE
NOCACHE;