--+Reboard
--renum id contents regdate ref

CREATE TABLE REBOARD
(RENUM NUMBER(10) CONSTRAINT REBOARD_RENUM_PK PRIMARY KEY,
ID VARCHAR2(50),
CONTENTS CLOB,
REGDATE DATE,
REF NUMBER(10));

CREATE SEQUENCE REBOARD_RENUM_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE
NOCYCLE;