CREATE TABLE FILEUPLOADTEST
(FNO NUMBER(10) PRIMARY KEY,
TITLE VARCHAR2(100),
WRITER VARCHAR2(50),
CONTENTS VARCHAR2(1000),
FILEPATH VARCHAR2(1000));

CREATE SEQUENCE FILEUPLOADTEST_FNO_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
NOCACHE
NOCYCLE
